services:
  ecos-cms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:mysql://ecos-cms-db:3306/ecos_cms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=ecos_cms
      - SPRING_DATASOURCE_PASSWORD=ecos_cms
      - JWT_SECRET=bWktcHJveWVjdG8tcG9kc3RyZWFtLWVzLWluY3JlaWJsZS15LWVzdGEtZXMtbWktY2xhdmUtc2VjcmV0YS0yMDI1
      - SPRING_MAIL_USERNAME=ecoscms52@gmail.com
      - SPRING_MAIL_PASSWORD=ptsj uxif urds bdfg
    depends_on:
      ecos-cms-db:
        condition: service_healthy
    networks:
      - ecos-network
    restart: unless-stopped

  ecos-cms-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ecos_cms
      - MYSQL_USER=ecos_cms
      - MYSQL_PASSWORD=ecos_cms
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - ecos-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

volumes:
  mysql-volume:

networks:
  ecos-network:
    driver: bridge