spring:
  application:
    name: Ecos-cms

  # Configuración de la conexión a la base de datos MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/ecos_cms
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Configuración de HikariCP
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000

  # Configuración de Hibernate y JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Configuración de la conexión SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    debug: true

  # Activar el perfil "local" para desarrollo
  profiles:
    active: local

# Configuración personalizada de email
edtech:
  email:
    max-attachment-size: 10485760
    default-from: ${MAIL_USERNAME}

# Configuración del servidor
server:
  address: 0.0.0.0
  port: 8088
  forward-headers-strategy: native

# Configuración JWT
jwt:
  secret: ${jwt.secret}
  expiration: 86400000

# Configuración de logging
debug: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data: DEBUG
      hibernate:
        SQL: DEBUG
        type: TRACE
        orm:
          jdbc:
            bind: TRACE
    com:
      edtech: DEBUG

# Configuración de Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    url: /api-docs
  show-actuator: true

# Actuator - Monitor
management:
  server:
    port: 9090